# Generated by Django 4.2.6 on 2023-11-11 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customer_current_location_customer_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='rider',
            name='phone_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
