version: "3.9"

services:

  app:
    build:
      context: .
      args:
        - MODE=dev
    ports:
      - "8019:80"
    volumes:
      - "/app/scripts"
      - ./:/app

    environment:
      - DB_USER=rider_user
      - DB_NAME=riderapp
      - DB_PASSWORD=password
      - DB_HOST=db
    depends_on:
      - db
  # To connect to db with test data db_name = riderapp, db_user=rider_user, db_password = password


  db:
    build:
      context: ./db
    environment:
      - POSTGRES_PASSWORD=password
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    ports:
      - "9020:5432"

volumes:
  dev-db-data: