# Generated by Django 4.2.6 on 2023-11-11 16:50

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_customer_current_location_customer_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RideObject',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('ride_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('pickup_location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('drop_off_location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('pickup_time', models.DateTimeField(blank=True, null=True)),
                ('drop_off_time', models.DateTimeField(blank=True, null=True)),
                ('deal_price', models.IntegerField(blank=True, null=True)),
                ('ride_booked', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.customer')),
                ('rider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.rider')),
            ],
        ),
    ]
