# Generated by Django 4.2.6 on 2023-11-11 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides_mgmt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rideobject',
            name='id',
            field=models.BigIntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
